### ISSUE TITLE
[Common] AWS S3 연동

### ISSUE THREAD

**Issue by hanjo8813** [prgrms-be-devcourse/BEDV1_OurHome#22]
- ourhome-common 모듈에 구현 예정
- yaml 파일을 읽어와야 하므로 많은 시간 소요.......예정....

### 참고

https://devlog-wjdrbs96.tistory.com/302

https://jojoldu.tistory.com/300

**Comment by hanjo8813** [comment]
승훈님 계정에 IAM 계정(S3 접근권한만 가짐) 생성, 액세스 키는 슬랙에.

![image](https://user-images.githubusercontent.com/71180414/139204709-0d7ec617-1c30-4f70-85f6-3e737ca874a1.png)

**Comment by hanjo8813** [comment]
### endpoint 모듈

- `application.yaml`에 aws 설정 추가
- 일단 intelliJ 환경변수로 키 설정

```yaml
# AWS S3 설정
cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_KEY}
    s3:
      bucket: ${AWS_BUCKET}
    region:
      static: ap-northeast-2
    stack:
      auto: false
```

### common 모듈 

- `build.gradle` 에 aws 의존성 추가
- utils 패키지에 s3업로더 컴포넌트 추가
